name: curating-legs
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - --index-url https://download.pytorch.org/whl/cu118
    - torch 
    - torchvision 
    - torchaudio 
    - --index-url https://pypi.org/simple
    - scipy
    - matplotlib
    - mujoco
    - gymnasium==0.29.1
